config/routes.rb
Rails.application.routes.draw do

  resources :contact_forms

  resources :items
  get 'landing/splash'
  get 'landing/faq'
  get 'landing/terms'

  devise_for :users

  resources :users, only: [:show] do
    resources :orders do
      resources :order_items, only: [:create, :update, :destroy]
    end
    resources :accounts, only: [:create, :new, :show]
    resources :appointments
  end

  root :to => 'landing#splash'
  get 'dashboard', to: 'landing#dash_app', as: :landing_dash_app
  get 'request', to: 'client#req', as: :client_req
  get 'wardrobe', to: 'client#wardrobe', as: :client_wardrobe
  get 'clients', to: 'internal#clientele', as: :internal_clientele
  get 'inventory', to: 'internal#inventory', as: :internal_inventory
  get 'add_order', to: 'orders#add', as: :orders_add
  get 'add_appt', to: 'appointments#add', as: :appointments_add
end

app/models/account.rb
class Account < ActiveRecord::Base
	belongs_to :user
	belongs_to :client, :class_name => 'User'

	validates :client_id, uniqueness: true
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :user
  belongs_to :appointment_status

  validates_presence_of :datetime, :location

  def status
    appointment_status.name
  end
end

app/models/appointment_status.rb
class AppointmentStatus < ActiveRecord::Base
	has_many :appointments
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
	attribute :name
	attribute :email
	attribute :phone
	attribute :code

	def headers
	{
		:subject => "Lapel Interest",
		:to => "concierge@lapel.co",
		:from => %("#{name} <#{email}>")
	}
	end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :item_category
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
  mount_uploader :avatar, AvatarUploader

  def cat
    item_category.name
  end
end

app/models/item_category.rb
class ItemCategory < ActiveRecord::Base
	has_many :items
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :order_status
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items

  before_create :set_order_status
  validates_presence_of :delivery

  def subtotal
    amounts = []
    order_items.each do |order_item|
      amounts << order_item.price
    end
    return amounts.inject(:+)
  end

  def status
    order_status.name
  end

  private

    def set_order_status
      self.order_status_id = 1
    end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :order
  #
  # validates_presence_of :item, :order

  # before_save :finalize

  def price
    item.price
  end

  private

    def finalize
      self[:total] = quantity * item.price
    end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
	has_many :orders, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  has_many :appointments
  has_many :accounts
  has_many :clients, :through => :accounts
  has_many :inverse_accounts, :class_name => "Account", :foreign_key => "client_id"
  has_many :liaisons, :through => :inverse_accounts, :source => :user
  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  # RETURN A LIAISON'S CLIENTS' ORDERS
  def client_orders
    self.clients.map(&:orders)
  end

  # RETURN A LIAISON'S CLIENTS' APPOINTMENTS
  def client_appointments
    self.clients.map(&:appointments)
  end

  # RETURN A USER'S LIAISON
  def liaison
    inverse_accounts.last.user
  end

  # RETURN TRUE IF USER IS A LIAISON
  def liaison?
    role == 'liaison'
  end

  # RETURN TRUE IF USER IS A CLIENT
  def client?
    role == 'client'
  end

  # RETURNS A CLIENT'S DELIVERED ITEMS
  def wardrobe_items
    wardrobe = []
    orders.where(order_status: 4).each do |order|
      order.items.each do |item|
        wardrobe << item
      end
    end
    return wardrobe
  end

  # RETURNS A CLIENT'S SPEND
  def spend
    amounts = []
    orders.where(order_status_id: 4).each do |order|
      amounts << order.subtotal
    end
    return amounts.inject(:+)
  end
end

app/controllers/internal_controller.rb
class InternalController < ApplicationController
	before_action :authenticate_user!

	def clientele
	end

	def inventory
		@items = Item.all
		@item_categories = ItemCategory.all
	end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/internal_helper.rb
module InternalHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/internal/_clientprofile.html.erb
<div class="profile_page row">
	<div class="col-md-10 col-md-offset-2">
			<div class="header text-center">
			<h3><%= @user.name %></h3>
			<% if @user.client? %>
				<p><%= "last order : #{@user.orders.last.status} - #{@user.orders.last.updated_at.strftime("%m/%d/%y")}" %></p>
				<p><%= "last appointment : #{@user.appointments.last.status} - #{@user.appointments.last.datetime.strftime("%m/%d/%y")}" %></p>
				<p class="order_status"><%= "Current Spend : $#{@user.spend}" %></p>
			<% end %>
	 		</div>

		<div class="main_content row">
			<div class="row col-md-6">
				<div class="info col-md-12 text-center">
					<div class="user_info">
						<h4>USER INFO</h4>
						<% if @user.phone %>
						<p><%= "Phone: #{@user.phone}" %></p>
						<% else %>
						<p>Phone: <small>WE DON'T HAVE THIS PHONE</small></p>
						<% end %>
						<% if @user.address %>
						<p><%= "Address: #{@user.address}" %></p>
						<% else %>
						<p>Address: <small>WE DON'T HAVE THIS ADDRESS</small></p>
						<% end %>
					</div>
				</div>

				<div class="orders col-md-12 text-center">
					<div id="orders_text">
					<% if @user.client? %>
						<h4>ORDERS</h4>
						<% if @user.orders.size == 0 %>
							<p>No orders to show. Add an order</p>
						<% else %>
							<% @user.orders.each do |order| %>
								<div>
									<p>
										<%= "#{order.status} - #{order.updated_at.strftime("%m/%d/%y")}" %>
										<%= "$#{order.subtotal}" %>
										<%= link_to "SEE MORE", [order.user, order], class: "see-more-link" %>
									</p>
								</div>
							<% end %>
						<% end %>
						<p><%= link_to "ADD ORDER", new_user_order_path(@user), class: "see-more-link"%></p>
					<% end %>
					</div>
				</div>
			</div>

			<div class="col-md-6">
			<% if @user.client? %>
				<%= render 'internal/measurements' %>
			<% end %>
			</div>
		</div>
		<h4 id="back_link"><%= link_to "BACK", :back %></h4>
	</div>
</div>

app/views/internal/_internaldashcontent.html.erb
<h3 class="text-center" id="dash-head">DASHBOARD</h3>
<div class="row status_head">
  <div class="col-md-3">
    <h4>REQUESTED</h4>
  </div>
  <div class="col-md-3">
    <h4>PROCESSED</h4>
  </div>
  <div class="col-md-3">
    <h4>DELIVERED</h4>
  </div>
  <div class="col-md-3">
    <h4>COMPLETED</h4>
  </div>
</div>


<div class="activity_list row">
   <div class="act_list col-md-3" id="requested">
      <% if @order_statuses.find(1).orders.length > 0 %>
         <% @order_statuses.find(1).orders.each do |order| %>
          <%= link_to([order.user, order]) do %>
            <div class="order_box">
               <div class="order_text">
                <h6><%= order.user.name %></h6>
                <p class="small"><%= "#{order.items.count} items, $#{order.subtotal}" %></p>
                <p class="small"><%= "last updated #{time_ago_in_words(order.updated_at)} ago" %></p>
             </div>
            </div>
          <% end %>
        <% end %>
      <% else %>
         <p>No requested orders</p>
      <% end %>
      <% if @appointment_statuses.find(1).appointments.length > 0 %>
         <% @appointment_statuses.find(1).appointments.each do |appt| %>
           <%= link_to([appt.user, appt]) do %>
               <div class="appt_box">
                  <div class="appt_text">
                     <h6><%= appt.user.name %></h6>
                     <p class="small">
                       <%= "#{appt.role} scheduled" %>
                       <%= "on #{appt.datetime.strftime("%m/%d/%y, %l:%M %p")}" %>
                       <%= "at #{appt.location}" %>
                     </p>
                  </div>
               </div>
            <% end %>
        <% end %>
      <% else %>
        <p>No requested appointments.</p>
      <% end %>
   </div>
   <div class="act_list col-md-3" id="processing">

      <% if @order_statuses.find(2).orders.length > 0 %>
         <% @order_statuses.find(2).orders.each do |order| %>
         <%= link_to([order.user, order]) do %>
           <div class="order_box">
             <div class="order_text">
               <h6><%= order.user.name %></h6>
               <p class="small"><%= "#{order.items.count} items, $#{order.subtotal}" %></p>
               <p class="small"><%= "last updated #{time_ago_in_words(order.updated_at)} ago" %></p>
            </div>
           </div>
         <% end %>
            <% end %>
      <% else %>
         <p>No processed orders</p>
      <% end %>
      <% if @appointment_statuses.find(2).appointments.length > 0 %>
         <% @appointment_statuses.find(2).appointments.each do |appt| %>
         <%= link_to([appt.user, appt]) do %>
           <div class="appt_box">
             <div class="appt_text">
                 <h6><%= appt.user.name %></h6>
                 <p class="small">
                   <%= "#{appt.role} scheduled" %>
                   <%= "on #{appt.datetime.strftime("%m/%d/%y, %l:%M %p")}" %>
                   <%= "at #{appt.location}" %>
                 </p>
              </div>
           </div>
          <% end %>
            <% end %>
         <% else %>
         <p>No processed appointments</p>
         <% end %>
   </div>
   <div class="act_list col-md-3" id="delivered">

      <% if @order_statuses.find(3).orders.length > 0 %>
         <% @order_statuses.find(3).orders.each do |order| %>
         <%= link_to([order.user, order]) do %>
           <div class="order_box">
             <div class="order_text">
                  <h6><%= order.user.name %></h6>
                  <p class="small"><%= "#{order.items.count} items, $#{order.subtotal}" %></p>
                  <p class="small"><%= "last updated #{time_ago_in_words(order.updated_at)} ago" %></p>
               </div>
           </div>
         <% end %>
        <% end %>
      <% else %>
         <p>No delivered orders</p>
      <% end %>
   </div>
   <div class="act_list col-md-3" id="completed">

      <% if @order_statuses.find(4).orders.length > 0 %>
         <% @order_statuses.find(4).orders.each do |order| %>
         <%= link_to([order.user, order]) do %>
           <div class="order_box">
             <div class="order_text">
               <h6><%= order.user.name %></h6>
               <p class="small"><%= "#{order.items.count} items, $#{order.subtotal}" %></p>
               <p class="small"><%= "last updated #{time_ago_in_words(order.updated_at)} ago" %></p>
            </div>
           </div>
         <% end %>
        <% end %>
      <% else %>
         <p>No completed orders</p>
      <% end %>

      <% if @appointment_statuses.find(4).appointments.length > 0 %>
         <% @appointment_statuses.find(4).appointments.each do |appt| %>
         <%= link_to([appt.user, appt]) do %>
           <div class="appt_box">
             <div class="appt_text">
                 <h6><%= appt.user.name %></h6>
                 <p class="small">
                   <%= "#{appt.role} scheduled" %>
                   <%= "on #{appt.datetime.strftime("%m/%d/%y, %l:%M %p")}" %>
                   <%= "at #{appt.location}" %>
                 </p>
              </div>
           </div>
          <% end %>
            <% end %>
         <% else %>
         <p>No completed appointments</p>
         <% end %>
   </div>
</div>

app/views/internal/_internalside.html.erb
  <%= image_tag('lapel_black.png', class: "logo-side text-center") %>
  <div class="profile_pic text-center">
     <%= link_to image_tag('http://robohash.org/my-own-slug.png?size=100x100', id: "pro_image", class: "img-circle"), edit_user_registration_path %>
     <p class="small">
       <%= current_user.name %><br/>
       <%= current_user.role %>
     </p>
  </div>

  <div class="navigation">
     <ul class="nav_list text-center">
        <li data-toggle="tooltip" data-placement="right" title="DASHBOARD" class="side-tooltip"><%= link_to image_tag('dash.png', class: 'img-sidebar'), landing_dash_app_path %></li>
        <li data-toggle="tooltip" data-placement="right" title="CLIENTS" class="side-tooltip"><%= link_to image_tag('clients.png', class: 'img-sidebar'), internal_clientele_path %></li>
        <li data-toggle="tooltip" data-placement="right" title="INVENTORY" class="side-tooltip"><%= link_to image_tag('inventory.png', class: 'img-sidebar'), internal_inventory_path %></li>
        <li class="panel" role="button" data-toggle="collapse" href="#options_accord" aria-expanded="false" aria-controls="options_accord"><%= image_tag('gear.png', class: 'img-sidebar') %></li>
        <ul class="panel collapse" id="options_accord">
           <li><%= link_to "ADD ACCOUNT", new_user_account_path(current_user), class: "list_lg" %></li>
           <li><%= link_to "ADD ITEM", new_item_path, class: "list_lg" %></li>
           <li><%= link_to "ADD ORDER", orders_add_path, class: "list_lg" %></li>
           <li><%= link_to "ADD APPT", appointments_add_path, class: "list_lg" %></li>
           <li><%= link_to 'LOGOUT', destroy_user_session_path, class: "list_lg", method: :delete %></li>
        </ul>
     </ul>
  </div>

app/views/internal/_measurements.html.erb
<div class="client_measurements">
   <h4 class="text-center">MEASUREMENTS</h4>
   <ul>
     <div class="row">
       <div class="col-xs-6">
        <li>
           <% if @user.neck %>
           <p>NECK: <%= @user.neck %></p>
           <% else %>
           <p>NECK:<small>Contact LIAISON</small></p>
         <% end %>
        </li>

        <li>
           <% if @user.chest %>
           <p>CHEST: <%= @user.chest %></p>
           <% else %>
           <p>CHEST: <small>Contact LIAISON</small></p>
           <% end %>
        </li>

        <li>
           <% if @user.length %>
           <p>LENGTH: <%= @user.length %></p>
           <% else %>
           <p>LENGTH: <small>Contact LIAISON</small></p>
           <% end %>
        </li>

        <li>
           <% if @user.sleeve %>
           <p>SLEEVE: <%= @user.sleeve %></p>
           <% else %>
           <p>SLEEVE: <small>Contact LIAISON</small></p>
           <% end %>
        </li>

        <li>
           <% if @user.waist %>
           <p>WAIST: <%= @user.waist %></p>
           <% else %>
           <p>WAIST: <small>Contact LIAISON</small></p>
           <% end %>
        </li>
      </div>

      <div class="col-xs-6">
        <li>
           <% if @user.inseam %>
           <p>INSEAM: <%= @user.inseam %></p>
           <% else %>
           <p>INSEAM: <small>Contact LIAISON</small></p>
           <% end %>
        </li>

        <li>
           <% if @user.shoe %>
           <p>SHOE SIZE: <%= @user.shoe %></p>
           <% else %>
           <p>SHOE SIZE: <small>Contact LIAISON</small></p>
           <% end %>
        </li>

        <li>
           <% if @user.suit %>
           <p>SUIT SIZE: <%= @user.suit %></p>
           <% else %>
           <p>SUIT SIZE: <small>Contact LIAISON</small></p>
           <% end %>
        </li>

        <li>
           <% if @user.pant %>
           <p>PANT SIZE: <%= @user.pant %></p>
           <% else %>
           <p>PANT SIZE: <small>Contact LIAISON</small></p>
           <% end %>
        </li>
      </div>
    </div>
   </ul>
</div>

app/views/internal/clientele.html.erb
<% if current_user.liaison? %>
<div class="row">
   <div class="sidebar">
     <%= render "internal/internalside" %>
   </div>
   <div class="content" id="content">
     <h3 id="clientele_title" class="text-center">CLIENTELE</h3>
     <div class="clientele">
       <div class="table_titles">
          <div class="row">
             <div class="col-md-3">
                <h4>Client</h4>
             </div>
             <div class="col-md-3">
                <h4>Last Order</h4>
             </div>
             <div class="col-md-4">
               <h4>Last Appt</h4>
             </div>
             <div class="col-md-2">
               <h4>Spend</h4>
             </div>
          </div>
       </div>
       <div class="row">
         <div class="client_list row">
           <% if current_user.clients.length > 0 %>
              <% current_user.clients.each do |client| %>
              <div class="row client_row">
                 <div class="col-md-3">
                    <p><%= link_to client.name, user_path(client), class: "link" %></p>
                 </div>
                 <div class="col-md-3">
                  <% if client.orders.nil? %>
                    <p><%= link_to "Add Order", new_user_orders_path(client) %>
                  <% else %>
                    <p>
                      <%= link_to client.orders.last.status, [client, client.orders.last], class: "link" %>
                      <%= " - $#{client.orders.last.subtotal}" %>
                    </p>
                  <% end %>
                 </div>
                 <div class="col-md-4">
                  <% if client.appointments.nil? %>
                    <p><%= link_to "Add Appointment", new_user_appointments_path(client) %>
                  <% else %>
                    <p>
                       <%= link_to client.appointments.last.status, [client, client.appointments.last], class: "link" %>
                       <%= client.appointments.last.datetime.strftime("%m/%d/%y, %l:%M %p") %>
                    </p>
                  <% end %>
                 </div>
                 <div class="col-md-2">
                   <% if client.spend == nil %>
                     <p class="small">0 delivered</p>
                   <% else %>
                     <p><%= "$#{client.spend}" %></p>
                   <% end %>
                 </div>
              </div>

               <% end %>
           <% else %>
              <div class="client_negative text-center">
                 <h3>YOU HAVE NO CLIENTS.</h3>
              </div>

              <div class="extra_prompts">
                 <h4>GO SELL SOMETHING!</h4>
              </div>
           <% end %>
         </div>
       </div>
     </div>
   </div>
</div>
<% else %>
<div class="row">
   <%= render "client/navbar" %>
   <div class="client-content text-center">
     <h5>Unauthorized action</h5>
     <%= link_to "BACK", :back %>
   </div>
</div>
<% end %>