config/routes.rb
Rails.application.routes.draw do

  resources :contact_forms

  resources :items
  get 'landing/splash'
  get 'landing/faq'
  get 'landing/terms'

  devise_for :users

  resources :users, only: [:show] do
    resources :orders do
      resources :order_items, only: [:create, :update, :destroy]
    end
    resources :accounts, only: [:create, :new, :show]
    resources :appointments
  end

  root :to => 'landing#splash'
  get 'dashboard', to: 'landing#dash_app', as: :landing_dash_app
  get 'request', to: 'client#req', as: :client_req
  get 'wardrobe', to: 'client#wardrobe', as: :client_wardrobe
  get 'clients', to: 'internal#clientele', as: :internal_clientele
  get 'inventory', to: 'internal#inventory', as: :internal_inventory
  get 'add_order', to: 'orders#add', as: :orders_add
  get 'add_appt', to: 'appointments#add', as: :appointments_add
end

app/models/account.rb
class Account < ActiveRecord::Base
	belongs_to :user
	belongs_to :client, :class_name => 'User'

	validates :client_id, uniqueness: true
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :user
  belongs_to :appointment_status

  validates_presence_of :datetime, :location

  def status
    appointment_status.name
  end
end

app/models/appointment_status.rb
class AppointmentStatus < ActiveRecord::Base
	has_many :appointments
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
	attribute :name
	attribute :email
	attribute :phone
	attribute :code

	def headers
	{
		:subject => "Lapel Interest",
		:to => "concierge@lapel.co",
		:from => %("#{name} <#{email}>")
	}
	end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :item_category
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
  mount_uploader :avatar, AvatarUploader

  def cat
    item_category.name
  end
end

app/models/item_category.rb
class ItemCategory < ActiveRecord::Base
	has_many :items
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :order_status
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items

  before_create :set_order_status
  validates_presence_of :delivery

  def subtotal
    amounts = []
    order_items.each do |order_item|
      amounts << order_item.price
    end
    return amounts.inject(:+)
  end

  def status
    order_status.name
  end

  private

    def set_order_status
      self.order_status_id = 1
    end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :order
  #
  # validates_presence_of :item, :order

  # before_save :finalize

  def price
    item.price
  end

  private

    def finalize
      self[:total] = quantity * item.price
    end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
	has_many :orders, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  has_many :appointments
  has_many :accounts
  has_many :clients, :through => :accounts
  has_many :inverse_accounts, :class_name => "Account", :foreign_key => "client_id"
  has_many :liaisons, :through => :inverse_accounts, :source => :user
  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  # RETURN A LIAISON'S CLIENTS' ORDERS
  def client_orders
    self.clients.map(&:orders)
  end

  # RETURN A LIAISON'S CLIENTS' APPOINTMENTS
  def client_appointments
    self.clients.map(&:appointments)
  end

  # RETURN A USER'S LIAISON
  def liaison
    inverse_accounts.last.user
  end

  # RETURN TRUE IF USER IS A LIAISON
  def liaison?
    role == 'liaison'
  end

  # RETURN TRUE IF USER IS A CLIENT
  def client?
    role == 'client'
  end

  # RETURNS A CLIENT'S DELIVERED ITEMS
  def wardrobe_items
    wardrobe = []
    orders.where(order_status: 4).each do |order|
      order.items.each do |item|
        wardrobe << item
      end
    end
    return wardrobe
  end

  # RETURNS A CLIENT'S SPEND
  def spend
    amounts = []
    orders.where(order_status_id: 4).each do |order|
      amounts << order.subtotal
    end
    return amounts.inject(:+)
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  before_action :authenticate_user!, only: :dash_app
  def splash
    @contact_form = ContactForm.new
  end

  def dash_app
    @items = Item.all
    @order_statuses = OrderStatus.all
    @item_categories = ItemCategory.all
    @user = current_user
    @appointment_statuses = AppointmentStatus.all
  end

  def faq
     @user = current_user
  end

  def terms
     @user = current_user
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/internal_helper.rb
module InternalHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/landing/dash_app.html.erb
<% if current_user.liaison? %>
<div class="row rowwithnothing">
   <div class="sidebar">
     <%= render "internal/internalside" %>
   </div>
   <div class="content" id="content">
     <div class="dashboard_activities">
       <div class="row">
          <%= render "internal/internaldashcontent" %>
       </div>
    </div>
   </div>
</div>
<% elsif current_user.client? %>
  <%= render "client/navbar" %>
  <div class="client-content">
      <%= render "client/dashcontent" %>
  </div>
<% else %>
  <h5>There seems to be an error with your account, please contact concierge@lapel.co</h5>
<% end %>



<script type="text/javascript">
$(document).ready(function () {
// Handler for .ready() called.
$('html, body').animate({
     scrollTop: $('#content').offset().top
}, 'slow');
});
</script>

app/views/landing/faq.html.erb
<div class="row">
   <div class="faq-block">
      <div class="faq-header">
         <h3 class="text-center">FAQ</h3>
      </div>

      <div class="faq-list-block">
         <ul class="faq-list">
            <li>
               <h4>What do you do?</h4>
               <h5>Lapel is a concierge service for menswear that melds the old-world traditions of English haberdasheries with the seamlessness that today’s technology provides. We focus our time and attention on reforming the antiquated practices surrounding men’s clothing that our clients deal with regularly.</h5>
            </li>
            <li>
               <h4>Where is Lapel available?</h4>
               <h5>Lapel services a select group of gentlemen in California and New York, through established partnerships with Athletic, Yacht, and Country Clubs. We’ll be arriving in the Dallas/Austin region, the Chicago area, and the Greater Northeastern U.S. in Q2 of 2016.</h5>
            </li>

            <li>
               <h4>How do I participate?</h4>
               <h5>As previously noted, the majority of clients are the result of either club affiliation or referrals from existing Lapel Gentlemen. Membership is severely limited, as high volume is oft associated with diminishing service.<br />For all membership inquiries, please apply at www.lapel.co.<br />However, it is highly recommended that any application come attached with the endorsement of a Gentleman in good standing.</h5>
            </li>
         </ul>
      </div>

      <div class="return-button text-center">
         <%= link_to "BACK", :back %>
      </div>
   </div>
</div>

app/views/landing/splash.html.erb
<!-- HEADER -->
<div class="infosite">
   <div id="header" class="row">
       <div id="delay-fade" class="col-xs-12 animated fadeIn delay text-center">
           <%= image_tag("lapel-white.png", id: "logo-header", class: "header img-responsive") %>
           <h2 id="tagline" class="heading">Welcome to better</h2>
           <button type="button" class="btn btn-top animated zoomIn delay" data-toggle="modal" data-target="#apply">Apply</button>
           <!-- <a href="#"><button type="button" class="btn btn-top">Log In</button></a> -->
       </div>
   </div>

   <!-- VISION -->
   <div id="vision" class="row">
       <div class="col-xs-8 col-xs-offset-2 text-center">
   		<h2 id="vision-heading" class="heading wow animated fadeInUp">Simple, but significant.</h2>
       	<h3 id="vision-detail" class="wow animated fadeIn delay">LAPEL IS THE NEW PLATFORM FOR MENSWEAR,<br /> BUILT AROUND GENTLEMEN'S PREFERENCES EVERYWHERE.</h3>
       </div>
   </div>

   <!-- SERVICE -->
   <div id="service" class="row">
   	<div class="col-xs-12 heading text-center">
   		<h2 class="heading wow animated fadeInUp">Member Benefits</h2>
   	</div>
      <div class="services text-center">
          <div class="service-item col-xs-12 col-sm-4 text-center">
             <%= image_tag("calendar.png", class: "animated img-responsive wow grow delay-1") %>
             <h3 class="wow animated fadeIn delay-1" title="Fresh razor, clean underwear, toothpaste.">REFILLABLE<br/>ESSENTIALS</h3>
             <div class="overlay">
               <h4>Fresh razor, clean underwear, toothpaste.</h4>
             </div>
          </div>

          <div class="service-item col-xs-12 col-sm-4 text-center">
            <%= image_tag("closet.png", class: "animated img-responsive wow grow delay-1") %>
            <h3 class="wow animated fadeIn delay-1" title="Built around you and your lifestyle, we'll build or polish your entire closet.">WARDROBE<br/>CONSTRUCTION</h3>
              <div class="overlay">
                  <h4>Built around you and your lifestyle, we'll build or polish your entire closet.</h4>
              </div>
          </div>
      	<div class="service-item col-xs-12 col-sm-4 text-center">
      		<%= image_tag("box.png", class: "animated img-responsive wow grow delay-1") %>
            <h3 class="wow animated fadeIn delay-1" title="Have everything you want, delivered wherever you are, whenever you need it.">ON-DEMAND<br/>DELIVERY</h3>
              <div class="overlay">
                  <h4>Have everything you want, delivered wherever you are, whenever you need it.</h4>
              </div>
          </div>
      </div>
   </div>
   <script>
   $(document).ready(function() {
   $('.service-item > img')
      .mouseenter(function() {
         var overlayDiv = $(this).siblings('.overlay')
         if (!overlayDiv.is(":visible"))
            overlayDiv.fadeIn();
   });

   $('.service-item > .overlay')
      .mouseleave(function() {
         if ($(this).is(":visible"))
            $(this).fadeOut();
   });
});

   </script>

   <!-- FINAL -->

   <div id="final" class="row">
       <div id="launch" class="col-xs-12 text-center">

         <div class="launch-item launchpad-1 col-xs-12 col-sm-4">
       		<h2 id="la">Los Angeles</h2>
            <h4>SPRING 2015</h4>
            <button type="button" class="btn wow animated zoomIn delay hidebtn" data-toggle="modal" data-target="#apply">Apply</button>
       	</div>

         <div class="launch-item launchpad-2 col-xs-12 col-sm-4" id="city2">
       		<h2 id="sf">San Francisco</h2>
            <h4>SUMMER 2015</h4>
       		<button type="button" class="btn wow animated zoomIn delay" data-toggle="modal" data-target="#apply">Apply</button>
       	</div>

         <div class="launch-item launchpad-3 col-xs-12 col-sm-4" id="city3">
       		<h2 id="ny">New York</h2>
            <h4>FALL 2015</h4>
            <button type="button" class="btn wow animated zoomIn delay hidebtn" data-toggle="modal" data-target="#apply">Apply</button>
         </div>

       </div>

       <div id="footer" class="row rowwithnothing">
          <div id="footer-logo" class=col-xs-12>
             <div class="middle_logo text-center">
                <%= image_tag("lapel-white.png", height: '80', class: 'foot-img') %>
             </div>
             <div class="text-center" id='links'>
                <h6 id="word-links"class="inline-link"><%= link_to "TERMS OF SERVICE", landing_terms_path %> | <%= link_to "FAQ", landing_faq_path %></h6>
                <br />
                <br />
               <%= link_to image_tag('instagram_icon_white.png', height: '22'), 'https://instagram.com/lapelstyle/', class: 'inline-link' %>
               <%= link_to image_tag('angel-list-icon.png', height: '22'), "https://angel.co/lapel", class: 'inline-link' %>
             </div>
          </div>
       </div>
   </div>

   <!-- MODALS -->
   <!-- Apply Modal -->
   <div class="modal fade col-xs-12 col-md-8 col-md-offset-2" id="apply" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
       <div class="modal-dialog">
           <div class="modal-content">
               <div class="modal-header">
                   <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                   <h6 class="modal-title text-center" id="myModalLabel">Membership is by invitation only</h6>
               </div>
               <div class="modal-body text-center">
                 <%= form_for @contact_form do |f| %>
                 	<%= f.text_field :name, :required => false, class: 'form-control', placeholder: 'NAME' %>
                 	<%= f.text_field :email, :required => false, class: 'form-control', placeholder: 'EMAIL' %>
                 	<%= f.text_field :phone, :required => false, class: 'form-control', placeholder: 'PHONE' %>
                 	<%= f.text_field :code, :required => false, class: 'form-control', placeholder: 'INVITE CODE' %>
                 	<%= f.submit "Submit", class: 'btn btn-sm' %>
                 <% end %>
               </div>
             </div>
           </div>
       </div>
   </div>

   <!-- End INFOSITE -->
</div>

app/views/landing/terms.html.erb
<div class="row" id="terms_block">
   <div class="container">
      <div class="terms_header">
         <h2 class="text-center">TERMS OF SERVICE</h2>
      </div>
      <blockquote id="terms_top">
      Terms of Service ("Terms")     Last updated: July 27, 2015<br/>
      <br />
      Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the www.lapel.co website (the "Service") operated by Partridge, Inc ("us", "we", or "our").<br />
      <br />
      Your access to and use of the Service is conditioned upon your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who wish to access or use the Service.<br />
      <br />
      By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you do not have permission to access the Service.
      </blockquote>

      <h4>Links to other websites</h4>
      <blockquote>
         Our Service may contain links to third party web sites or services that are not owned or controlled by Partridge, Inc.<br />
         <br />
         Partridge, Inc has no control over, and assumes no responsibility for the content, privacy policies, or practices of any third party web sites or services. We do not warrant the offerings of any of these entities/individuals or their websites.<br />
         <br />
         You acknowledge and agree that Partridge, Inc shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such third party web sites or services.<br />
         <br />
         We strongly advise you to read the terms and conditions and privacy policies of any third party web sites or services that you visit.
      </blockquote>


      <h4>Termination</h4>
      <blockquote>
         We may terminate or suspend your access to the Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of the Terms.<br />
         <br />
         All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.
      </blockquote>

      <h4>Governing Law</h4>
      <blockquote>
         These Terms shall be governed and construed in accordance with the laws of California, United States, without regard to its conflict of law provisions.<br />
         <br />
         Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have had between us regarding the Service.
      </blockquote>

      <h4>Changes</h4>
      <blockquote>
         We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.<br />
         <br />
         By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use the Service.
      </blockquote>

      <h4>Contact Us</h4>
      <blockquote>If you have any questions about these Terms, please contact us at concierge@lapel.co.</blockquote>
   </div>
</div>