config/routes.rb
Rails.application.routes.draw do

  resources :contact_forms

  resources :items
  get 'landing/splash'
  get 'landing/faq'
  get 'landing/terms'

  devise_for :users

  resources :users, only: [:show] do
    resources :orders do
      resources :order_items, only: [:create, :update, :destroy]
    end
    resources :accounts, only: [:create, :new, :show]
    resources :appointments
  end

  root :to => 'landing#splash'
  get 'dashboard', to: 'landing#dash_app', as: :landing_dash_app
  get 'request', to: 'client#req', as: :client_req
  get 'wardrobe', to: 'client#wardrobe', as: :client_wardrobe
  get 'clients', to: 'internal#clientele', as: :internal_clientele
  get 'inventory', to: 'internal#inventory', as: :internal_inventory
  get 'add_order', to: 'orders#add', as: :orders_add
  get 'add_appt', to: 'appointments#add', as: :appointments_add
end

app/models/account.rb
class Account < ActiveRecord::Base
	belongs_to :user
	belongs_to :client, :class_name => 'User'

	validates :client_id, uniqueness: true
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :user
  belongs_to :appointment_status

  validates_presence_of :datetime, :location

  def status
    appointment_status.name
  end
end

app/models/appointment_status.rb
class AppointmentStatus < ActiveRecord::Base
	has_many :appointments
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
	attribute :name
	attribute :email
	attribute :phone
	attribute :code

	def headers
	{
		:subject => "Lapel Interest",
		:to => "concierge@lapel.co",
		:from => %("#{name} <#{email}>")
	}
	end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :item_category
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
  mount_uploader :avatar, AvatarUploader

  def cat
    item_category.name
  end
end

app/models/item_category.rb
class ItemCategory < ActiveRecord::Base
	has_many :items
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :order_status
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items

  before_create :set_order_status
  validates_presence_of :delivery

  def subtotal
    amounts = []
    order_items.each do |order_item|
      amounts << order_item.price
    end
    return amounts.inject(:+)
  end

  def status
    order_status.name
  end

  private

    def set_order_status
      self.order_status_id = 1
    end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :order
  #
  # validates_presence_of :item, :order

  # before_save :finalize

  def price
    item.price
  end

  private

    def finalize
      self[:total] = quantity * item.price
    end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
	has_many :orders, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  has_many :appointments
  has_many :accounts
  has_many :clients, :through => :accounts
  has_many :inverse_accounts, :class_name => "Account", :foreign_key => "client_id"
  has_many :liaisons, :through => :inverse_accounts, :source => :user
  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  # RETURN A LIAISON'S CLIENTS' ORDERS
  def client_orders
    self.clients.map(&:orders)
  end

  # RETURN A LIAISON'S CLIENTS' APPOINTMENTS
  def client_appointments
    self.clients.map(&:appointments)
  end

  # RETURN A USER'S LIAISON
  def liaison
    inverse_accounts.last.user
  end

  # RETURN TRUE IF USER IS A LIAISON
  def liaison?
    role == 'liaison'
  end

  # RETURN TRUE IF USER IS A CLIENT
  def client?
    role == 'client'
  end

  # RETURNS A CLIENT'S DELIVERED ITEMS
  def wardrobe_items
    wardrobe = []
    orders.where(order_status: 4).each do |order|
      order.items.each do |item|
        wardrobe << item
      end
    end
    return wardrobe
  end

  # RETURNS A CLIENT'S SPEND
  def spend
    amounts = []
    orders.where(order_status_id: 4).each do |order|
      amounts << order.subtotal
    end
    return amounts.inject(:+)
  end
end

app/controllers/client_controller.rb
class ClientController < ApplicationController
	before_action :authenticate_user!

	def req
	end

	def wardrobe
		@delivered_orders = current_user.orders.where(order_status_id: 4)
	end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/internal_helper.rb
module InternalHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/client/_dashcontent.html.erb
<div class="profile_page">
	<div class="row">
		<div class="main_content row">
			<div class="col-md-4">
				<div class="client-box">
					<div class="col-xs-3">
						<% if current_user.avatar? %>
							<%= image_tag(current_user.avatar.profile.url) %>
						<% else %>
							<%= image_tag('https://robohash.org/lapeldash', class: "img-circle img-item text-left") %>
						<% end %>
					</div>

					<div class="col-xs-9 details">
						<h5><%= current_user.name %></h5>
						<p class="small"><%= "Member since #{current_user.created_at.strftime('%b %d, %Y')}" %></p>
						<p class="small"><%= "Liaison : #{current_user.liaison.name}" %></p>
						<!-- <h6><%= link_to 'LOGOUT', destroy_user_session_path, method: :delete, class: 'log-out' %></h6> -->
					</div>
				</div>

				<div class="actions text-center">
					<span data-toggle="tooltip" data-placement="bottom" title="New Order">
						<%= link_to image_tag('cart.png'), new_user_order_path(current_user) %>
					</span>
					<span data-toggle="tooltip" data-placement="bottom" title="New Appointment">
						<%= link_to image_tag('appt.png'), new_user_appointment_path(current_user) %>
					</span>
					<span data-toggle="tooltip" data-placement="bottom" title="Email Liaison">
						<%= mail_to current_user.liaison.email, image_tag('mail.png') %>
					</span>
					<span data-toggle="tooltip" data-placement="bottom" title="Measurements">
						<%= image_tag('meas.png') %>
					</span>
				</div>


				<button type="button" class="btn btn-dropdown text-center" data-toggle="collapse" data-target="#detailsCollapse" aria-expanded="false" aria-controls="detailsCollapse">CONTACT INFO <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span></button>

				<div class="collapse" id="detailsCollapse">
					<div class="client-info">
						<div class="info_inset text-center">
							<% if current_user.address %>
							<p><%= "#{current_user.address}" %></p>
							<% else %>
							<p><small>NO ADDRESS ON FILE</small></p>
							<% end %>
							<% if current_user.email %>
							<p><%= "#{current_user.email}"%></p>
							<% else %>
							<p><small>NO EMAIL ON FILE</small></p>
							<% end %>
							<% if current_user.phone %>
							<p><%= "#{current_user.phone}"%></p>
							<% else %>
							<p><small>NO PHONE ON FILE</small></p>
							<% end %>
						</div>
					</div>
				</div>
			</div>

			<div class="col-md-4">
				<div class="appt-alert text-center">
					<% unless current_user.appointments.last.appointment_status_id == 4 %>
						<p class="light-head"><%= "#{current_user.appointments.last.role} appointment on" %></p>
						<h3><%= current_user.appointments.last.datetime.strftime('%A, %b %d') %></h3>
						<h3><%= current_user.appointments.last.datetime.strftime('%l:%M %p') %></h3>
						<p class="light-head">at</p>
						<h4><%= current_user.appointments.last.location %></h4>
					<% else %>
						<p>You have no scheduled appointments</p>
						<%= link_to "New Appointment", new_user_appointment_path(current_user) %>
					<% end %>
				</div>

				<div class="appt-history">
					<h5 class="text-center">Appointment History</h5>
					<div class="row">
						<% current_user.appointments.each do |appointment| %>
							<%= link_to([current_user, appointment]) do %>
							<div class="col-xs-4">
								<h6><%= appointment.datetime.strftime('%m/%d/%y') %></h6>
							</div>
							<div class="col-xs-4">
								<h6><%= appointment.location %></h6>
							</div>
							<div class="col-xs-4">
								<h6><%= appointment.status %></h6>
							</div>
							<% end %>
						<% end %>
					</div>
				</div>
			</div>


			<div class="col-md-4">

				<div class="order-alert text-center">
					<%= link_to([current_user, current_user.orders.last]) do %>
						<p><%= "order #{current_user.orders.last.status} on" %></p>
						<h3><%= current_user.orders.last.updated_at.strftime('%m/%d/%y') %></h3>
						<p class="small"><%= "#{current_user.orders.last.items.count} Items - $#{current_user.orders.last.subtotal}" %></p>
					<% end %>
					<div class="order-notes">
						<% if current_user.orders.last.order_status_id == 1 %>
							<p class="small"></p>
						<% elsif current_user.orders.last.order_status_id == 2 %>
							<p class="small"><%= link_to "Please review the curation", [current_user, current_user.orders.last] %></p>
						<% elsif current_user.orders.last.order_status_id == 3 %>
						  <p class="small"></p>
						<% else %>
						  <%= link_to "New order", new_user_order_path(current_user), class:'btn' %>
						<% end %>
					</div>
				</div>

				<div class="order-history">
					<h5 class="text-center">Order History</h5>
					<div class="row">
						<% current_user.orders.each do |order| %>
							<%= link_to([current_user, order]) do %>
								<div class="col-xs-4">
									<%= order.updated_at.strftime('%m/%d/%y') %>
								</div>
								<div class="col-xs-4">
									<%= order.status %>
								</div>
								<div class="col-xs-4">
									<%= "$#{order.subtotal}" %>
								</div>
							<% end %>
						<% end %>
					</div>
				</div>

				<div class="metrics text-center">
					<div class="placeholders">
						<%= image_tag('pie.png', height: "50") %>
						<%= image_tag('bar.png', height: "50") %>
						<%= image_tag('dash.png', height: "50") %>
					</div>
				</div>

			</div>
		</div>
	</div>
</div>

app/views/client/_navbar.html.erb
<div id="client-nav" class="text-center">
  <%= image_tag('lapel_white.png', class: "text-center") %>
  <nav class="navbar navbar-default text-center" role="navigation">
    <ul class="nav navbar-nav">
      <li role="presentation"><h5><%= link_to "Dashboard", landing_dash_app_path %></h5></li>
      <li role="presentation"><h5><%= link_to "Request", client_req_path %></h5></li>
      <li role="presentation"><h5><%= link_to "Wardrobe", client_wardrobe_path %></h5></li>
      <!-- <li><%= link_to 'LOGOUT', destroy_user_session_path, class: "list_lg", method: :delete %></li> -->
    </ul>
  </nav>
</div>

app/views/client/req.html.erb
<%= render "client/navbar" %>
<div class="client-content text-center">
	<div class="request row">
			<div class="col-sm-6">
				<%= link_to(new_user_appointment_path(current_user)) do %>
					<div class="req-box">
						<%= image_tag('fixed-wardrobe.svg', height: "190") %><br/>
						<h6>Schedule a styling</h6>
					</div>
				<% end %>
			</div>
			<div class="col-sm-6">
				<%= link_to(new_user_order_path(current_user)) do %>
					<div class="req-box">
						<%= image_tag('Outfits.png') %><br/>
						<h6>Submit an order</h6>
					</div>
				<% end %>
			</div>
	</div>
</div>

app/views/client/wardrobe.html.erb
<%= render "client/navbar" %>
<div class="client-content">
	<div class="wardrobe text-center">
		<div class="row">
			<% if @delivered_orders.length > 0 %>
				<% @delivered_orders.each do |order| %>
					<% order.items.each do |item| %>
						<div class="wardrobe-item col-md-4 text-left">
							<%= link_to item do %>
							 <div class="item_inlay row">
									<div class="col-md-5">
										<% if item.avatar? %>
												<%= image_tag( item.avatar.url, class: "img-item" ) %>
										<% else %>
												<%= image_tag('box.png', class: "img-circle img-item") %>
										<% end %>
									</div>
									<small class="col-md-7">
										<h5><%= item.brand %></h5><br/>
										<h6><%= item.name %><br/>
										<%= "$#{item.price}" %></h6>
									</small>
							 </div>
							 <% end %>
						</div>
					<% end %>
				<% end %>
			<% else %>
				<h5>Your wardrobe is empty, please submit an order.</h5>
				<%= link_to "BACK", :back %>
			<% end %>
		</div>
	</div>
</div>