config/routes.rb
Rails.application.routes.draw do

  resources :contact_forms

  resources :items
  get 'landing/splash'
  get 'landing/faq'
  get 'landing/terms'

  devise_for :users

  resources :users, only: [:show] do
    resources :orders do
      resources :order_items, only: [:create, :update, :destroy]
    end
    resources :accounts, only: [:create, :new, :show]
    resources :appointments
  end

  root :to => 'landing#splash'
  get 'dashboard', to: 'landing#dash_app', as: :landing_dash_app
  get 'request', to: 'client#req', as: :client_req
  get 'wardrobe', to: 'client#wardrobe', as: :client_wardrobe
  get 'clients', to: 'internal#clientele', as: :internal_clientele
  get 'inventory', to: 'internal#inventory', as: :internal_inventory
  get 'add_order', to: 'orders#add', as: :orders_add
  get 'add_appt', to: 'appointments#add', as: :appointments_add
end

app/models/account.rb
class Account < ActiveRecord::Base
	belongs_to :user
	belongs_to :client, :class_name => 'User'

	validates :client_id, uniqueness: true
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :user
  belongs_to :appointment_status

  validates_presence_of :datetime, :location

  def status
    appointment_status.name
  end
end

app/models/appointment_status.rb
class AppointmentStatus < ActiveRecord::Base
	has_many :appointments
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
	attribute :name
	attribute :email
	attribute :phone
	attribute :code

	def headers
	{
		:subject => "Lapel Interest",
		:to => "concierge@lapel.co",
		:from => %("#{name} <#{email}>")
	}
	end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :item_category
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
  mount_uploader :avatar, AvatarUploader

  def cat
    item_category.name
  end
end

app/models/item_category.rb
class ItemCategory < ActiveRecord::Base
	has_many :items
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :order_status
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items

  before_create :set_order_status
  validates_presence_of :delivery

  def subtotal
    amounts = []
    order_items.each do |order_item|
      amounts << order_item.price
    end
    return amounts.inject(:+)
  end

  def status
    order_status.name
  end

  private

    def set_order_status
      self.order_status_id = 1
    end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :order
  #
  # validates_presence_of :item, :order

  # before_save :finalize

  def price
    item.price
  end

  private

    def finalize
      self[:total] = quantity * item.price
    end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
	has_many :orders, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  has_many :appointments
  has_many :accounts
  has_many :clients, :through => :accounts
  has_many :inverse_accounts, :class_name => "Account", :foreign_key => "client_id"
  has_many :liaisons, :through => :inverse_accounts, :source => :user
  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  # RETURN A LIAISON'S CLIENTS' ORDERS
  def client_orders
    self.clients.map(&:orders)
  end

  # RETURN A LIAISON'S CLIENTS' APPOINTMENTS
  def client_appointments
    self.clients.map(&:appointments)
  end

  # RETURN A USER'S LIAISON
  def liaison
    inverse_accounts.last.user
  end

  # RETURN TRUE IF USER IS A LIAISON
  def liaison?
    role == 'liaison'
  end

  # RETURN TRUE IF USER IS A CLIENT
  def client?
    role == 'client'
  end

  # RETURNS A CLIENT'S DELIVERED ITEMS
  def wardrobe_items
    wardrobe = []
    orders.where(order_status: 4).each do |order|
      order.items.each do |item|
        wardrobe << item
      end
    end
    return wardrobe
  end

  # RETURNS A CLIENT'S SPEND
  def spend
    amounts = []
    orders.where(order_status_id: 4).each do |order|
      amounts << order.subtotal
    end
    return amounts.inject(:+)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def new
    @item = Item.new
  end

  def show
  end

  def index
    @items = Item.all
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "Item was saved."
      redirect_to @item
    else
      flash[:error] = "There was an error. Please try again."
      render :new
    end
  end

  def update
    if @item.update_attributes(item_params)
      flash[:notice] = "Item was updated."
      redirect_to @item
    else
      flash[:error] = "There was an error. Please try again."
      render :new
    end
  end

  def destroy
    if @item.destroy
      flash[:notice] = "Item was deleted."
      redirect_to items_path
    else
      flash[:error] = "Item was not deleted. Please try again."
      render @item
    end
  end

  private

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :price, :cost, :brand, :category_id, :avatar)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/internal_helper.rb
module InternalHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.erb
<div class="row">
   <% if current_user.liaison? %>
   <div class="sidebar">
      <%= render "internal/internalside" %>
   </div>
     <h2 class="text-center">Edit</h2>
     <div class="container">
       <div class="row">
         <%= form_for @item do |f| %>
           <div class="col-md-4 col-md-offset-4">
             <div class="form-group">
               <%= f.text_field :name, placeholder: 'Item name', class: 'form-control' %>
             </div>

             <div class="form-group">
               <%= f.text_field :price, placeholder: 'Price', class: 'form-control' %>
             </div>

             <% if @item.avatar? %>
               <div class="form-group">
                 <p>Current image</p>
                 <%= image_tag( @item.avatar.url ) %>
               </div>
             <% end %>

             <div class="form-group">
                 <%= f.file_field :avatar %>
                 <%= f.hidden_field :avatar_cache %>
             </div>

     				<div class="form-group">
     					<%= f.text_field :cost, placeholder: 'Cost', class: 'form-control' %>
     				</div>

     				<div class="form-group">
     					<%= f.text_field :brand, placeholder: 'Brand', class: 'form-control' %>
     				</div>

             <div class="form-group">
               <%= f.select :item_category_id, options_from_collection_for_select(ItemCategory.all, "id", "name") %>
             </div>

             <div class="form-group">
               <%= f.submit "Send", class: 'btn btn-success' %>
             </div>
           </div>
         <% end %>
       </div>
     </div>
   <% else %>
     <%= render "client/navbar" %>
     <div class="client-content text-center">
       <h5>Not authorized to edit</h5>
       <%= link_to "BACK", :back %>
     </div>
   <% end %>

</div>

app/views/items/index.html.erb
<% if current_user.client? %>
<div class="row">
   <%= render "client/navbar" %>
   <div class="client-content text-center">
     <h5>Unauthorized action</h5>
     <%= link_to "BACK", :back %>
   </div>
</div>
<% else %>
 <div class="row">
    <div class="inventory">
      <h2 class="text-center">INVENTORY</h2>
      <%= link_to "Add Item", new_item_path %>
      <div class="item_list">
          <% if @items.length > 0 %>
             <% @items.each do |item| %>
                <div class="item col-md-3">
                   <h4><%= item.name %></h4>
                   <h5>$<%= item.price %></h5>
                   <h5>SEE MORE</h5>
                 </div>
                <% end %>
          <% else %>
             <h3>There are no items currently in stock.</h3>
          <% end %>
      </div>
    </div>
 </div>
<% end %>

app/views/items/new.html.erb
<div class="row">
   <% if current_user.liaison? %>
      <div class="sidebar">
         <%= render "internal/internalside" %>
      </div>
     <h2 class="text-center" id="item_add_header">ADD ITEM</h2>
     <div class="container">
       <div class="row">

            <%= form_for @item do |f| %>
              <div class="col-md-4 col-md-offset-4">

                 <div class="form-group">
                   <%= f.text_field :name, placeholder: 'Item name', class: 'form-control' %>
                 </div>

                 <div class="form-group">
                   <%= f.text_field :price, placeholder: 'Price', class: 'form-control' %>
                 </div>

        				<div class="form-group">
        					<%= f.text_field :cost, placeholder: 'Cost', class: 'form-control' %>
        				</div>

        				<div class="form-group">
        					<%= f.text_field :brand, placeholder: 'Brand', class: 'form-control' %>
        				</div>

        				<div class="form-group">
                  <%= f.select :item_category_id, options_from_collection_for_select(ItemCategory.all, "id", "name"), class: "form-control" %>
        				</div>

                    <!-- <div class="form-group">
                       <select id="categories" name="Category"><option>FOOTWEAR</option><option selected='selected'>OUTERWEAR</option><option>KNITWEAR</option><option>EYEWEAR</option><option>DRESS SHIRTS</option><option>TIES</option><option>TEES</option><option>PANTS</option><option>SUITING</option></select>
                    </div> -->

                   <div class="form-group text-center">
                     <%= f.submit "SAVE", class: 'btn-submit' %>
                   </div>

              </div>
            <% end %>
         </div>
         <div class="back_link col-md-4 col-md-offset-4 text-center">
           <%= link_to "Back", :back , class: "back_btn"%>
         </div>
     </div>
   <% else %>
     <%= render "client/navbar" %>
     <div class="client-content text-center">
       <h5>Unauthorized action</h5>
       <%= link_to "BACK", :back %>
     </div>
   <% end %>

</div>

app/views/items/show.html.erb
<div class="row">
   <% if current_user.client? %>
     <%= render "client/navbar" %>
     <div class="client-content" style="margin-top:15vh;">
       <div id="item-card">
          <div class="image-panel text-center">
             <% if @item.avatar? %>
             <%= image_tag( @item.avatar.url, height: "300" ) %>
            <% else %>
               <%= link_to image_tag('box.png', class: "img-circle img-item"), @item %>
            <% end %>
          </div>
          <div class="specs-panel text-left">
             <h5><%= "MODEL: #{@item.name}" %></h5>
             <h5><%= "BRAND: #{@item.brand}" %></h5>
             <h6><%= "PRICE: $#{@item.price}" %></h6>
             <h6 id="desc"><%= "DESCRIPTION:" %></h6>
             <h6><%= "#{@item.desc}" %></h6>

             <% if current_user.liaison? %>
                 <h6 class="text-right"><%= link_to "edit", edit_item_path(@item) %></h6>
             <% end %>
          </div>
       </div>
     </div>
   <% elsif current_user.liaison? %>
   <div class="sidebar">
      <%= render "internal/internalside" %>
   </div>
   <div class="client-content">
     <div id="item-card">
        <div class="image-panel text-center">
           <% if @item.avatar? %>
           <%= image_tag( @item.avatar.url, height: "300" ) %>
          <% else %>
             <%= link_to image_tag('box.png', class: "img-circle img-item"), @item %>
          <% end %>
        </div>
        <div class="specs-panel text-left">
           <h5><%= "MODEL: #{@item.name}" %></h5>
           <h5><%= "BRAND: #{@item.brand}" %></h5>
           <h6><%= "PRICE: $#{@item.price}" %></h6>
           <h6 id="desc"><%= "DESCRIPTION:" %></h6>
           <h6><%= "#{@item.desc}" %></h6>

           <% if current_user.liaison? %>
               <h6 class="text-right"><%= link_to "edit", edit_item_path(@item) %></h6>
           <% end %>
        </div>
     </div>
   </div>
   <% end %>
</div>

app/views/users/show.html.erb
<% if current_user.liaison? %>
<div class="row">
   <div class="sidebar">
      <%= render "internal/internalside" %>
   </div>
   <%= render 'internal/clientprofile' %>
</div>

<% else %>
<div class="row">
   <%= render 'client/dashcontent' %>   
</div>
<% end %>